name: Feature Request
description: Suggest a feature for Zegel
labels: ["enhancement"]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: A clear and concise description of the problem this feature would solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this feature relate to?
      options:
        - Library
        - CLI
        - GUI
        - Format Spec
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
